theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
idle-timeout = 50
line-number = "relative"
rulers = [80, 120]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "â”‚"
render = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]

[editor.whitespace.render]
newline = "none"
space = "none"
tab = "all"

[keys.insert]
C-s = ["normal_mode", ":write"]

[keys.normal]
C-q = ":quit"
C-s = ":write"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
c = ":buffer-close"
q = ":quit"
w = ":write"
