[helpers]

[default]
depends = []

[default.files]
"CLAUDE.md" = ""
"lefthook.yml" = ""
home-manager = ""
"scripts" = "~/.local/bin"
"dotter/claude" = "~/.claude"
"dotter/ssh" = "~/.ssh"
"dotter/config" = "~/.config"
"dotter/local" = "~/.local"

[default.variables]

[settings]
default_target_type = "automatic"
