[helpers]

[default]
depends = []

[default.files]
"CLAUDE.md" = ""
"lefthook.yml" = ""
home-manager = ""
scripts = ""
"dotter/default" = "~/.config"

[default.variables]

[settings]
default_target_type = "automatic"
