[helpers]

[default]
depends = []

[default.files]
"CLAUDE.md" = ""
"lefthook.yml" = ""
home-manager = ""
"scripts" = "~/.local/bin/switch.sh"
"dotter/ssh" = "~/.ssh"
"dotter/config" = "~/.config"

[default.variables]

[settings]
default_target_type = "automatic"
