[helpers]

[default]
depends = []

[default.files]
"CLAUDE.md" = ""
"lefthook.yml" = ""
home-manager = ""
"scripts/switch.sh" = "~/.local/bin/switch.sh"
"scripts/upgrade.sh" = "~/.local/bin/upgrade.sh"
"scripts/install.sh" = "~/.local/bin/install.sh"
"scripts/undeploy.sh" = "~/.local/bin/undeploy.sh"
"dotter/config" = "~/.config"

[default.variables]

[settings]
default_target_type = "automatic"
